# Generated by Django 4.2.20 on 2025-05-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donneurs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donneur',
        ),
    ]
